"use client";
const C=({r,s,red=false})=><div className="pt-card"><b className={red?"red":""}>{r}</b><span className={red?"red":""}>{s}</span></div>;
const P=({title,children,cls=""})=><section className={"pt-panel "+cls}><h3>{title}</h3>{children}</section>;
const Seat=({p,st,cls=""})=><div className={"pt-seat "+cls}><i>●</i><b>{p}</b><small>{st} BB</small></div>;
export default function PurpleTemplate(){
 const menu=[["♠","TREINO","PRATIQUE COM SPOTS REAIS"],["▥","ANÁLISE","ESTATÍSTICAS E DESEMPENHO"],["▣","HISTÓRICO","SUAS MÃOS E EVOLUÇÃO"],["☷","FILTROS","PERSONALIZE SEU TREINO"],["◆","APRENDER","CONCEITOS E ESTRATÉGIAS"],["⚙","CONFIGURAÇÕES","PREFERÊNCIAS DO APP"]];
 return <main className="pt-app">
 <header><button className="pt-icon">☰</button><div className="pt-brand"><div className="pt-logo">SH</div><div><h1>STACKUP HOLD’EM</h1><h2>PRO TRAINER</h2></div></div><div className="pt-tools"><button>▥</button><button>♛</button><button>⚙</button></div><em>“TREINE. ENTENDA. EVOLUA.”</em></header>
 <nav className="pt-status">{[["FASE","TREINO"],["STREET","FLOP"],["POSIÇÃO","BTN"],["STACK","100 BB"],["SPOT","12/50"],["DIFICULDADE","MÉDIA"],["TEMPO","00:28"]].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</nav>
 <div className="pt-grid"><aside className="pt-menu">{menu.map((m,i)=><button key={m[1]} className={i===0?"on":""}><i>{m[0]}</i><span><b>{m[1]}</b><small>{m[2]}</small></span></button>)}<div className="pt-script">♠ O CAMINHO PARA<br/>MELHORES DECISÕES ♠</div></aside>
 <section className="pt-game"><div className="pt-table-zone"><div className="pt-table"><div className="pt-watermark"><b>SH</b><span>STACKUP<br/><small>HOLD’EM</small></span></div><Seat p="MP" st="100" cls="mp"/><Seat p="CO" st="100" cls="co"/><Seat p="UTG" st="100" cls="utg"/><Seat p="BTN" st="93.5" cls="btn"/><Seat p="SB" st="99.5" cls="sb"/><Seat p="BB" st="100" cls="bb"/><div className="pt-board"><C r="K" s="♠"/><C r="7" s="♥" red/><C r="4" s="♣"/></div><div className="pt-hole"><C r="A" s="♠"/><C r="Q" s="♥" red/></div><Seat p="HERO" st="93.5" cls="hero"/></div></div>
 <P title="QUAL É SUA AÇÃO?" cls="pt-action"><div className="pt-actions"><button className="fold">✕<b>FOLD</b></button><button className="check">−<b>CHECK</b></button><button className="call">♟<b>CALL</b><small>2.5 BB</small></button><button className="raise">↑<b>RAISE</b></button></div><div className="pt-range"><button>−</button><input type="range" defaultValue="55"/><output>7.5 BB</output><button>＋</button></div><div className="pt-nav"><button>⟳ REVER MÃO</button><button>← ANTERIOR</button><button>→ PRÓXIMO</button></div></P></section>
 <aside className="pt-side"><P title="◉ SPOT ATUAL"><p>♟ CASH GAME</p><p>⚙ 6-MAX</p><p>♟ 100 BB</p><p>◉ RAISE NO FLOP</p><p>◆ DRY BOARD</p></P><P title="▣ HISTÓRICO DA MÃO"><p>MP abre para 2.5 BB</p><p>CO folda</p><p>BTN paga</p><p>SB folda</p><p>BB paga</p></P><div className="pt-quote">♠<br/>“DISCIPLINA<br/>HOJE.<br/>RESULTADOS<br/>AMANHÃ.”</div></aside></div>
 <div className="pt-bottom"><P title="▥ ESTATÍSTICAS"><div className="pt-ring">78%</div><div className="pt-rate">TAXA DE ACERTO</div><div className="pt-numbers"><b>1.248<small>SPOTS</small></b><b>972<small>CORRETAS</small></b><b>276<small>INCORRETAS</small></b></div><div className="pt-ev">↗ EV MÉDIO <b>+0.28 BB</b></div></P><P title="✣ ÚLTIMAS MÃOS"><div className="pt-hands">{["✓ K♠7♥4♣  BTN · FLOP  +0.42 BB","✕ A♦J♠9♣5♥  CO · TURN  -1.20 BB","✓ Q♠Q♦2♣  MP · FLOP  +0.35 BB","✓ 8♣6♠J♥3♣  SB · TURN  +0.18 BB","✕ A♠K♦  BB · PRÉ-FLOP  -0.50 BB","✓ J♥T♠9♣  BTN · FLOP  +0.62 BB"].map((x,i)=><p className={i===1||i===4?"bad":""} key={x}>{x}</p>)}</div></P><P title="⚗ FILTROS RÁPIDOS"><div className="pt-list">{["POSIÇÕES · Todas","STACKS · Todos","FASE DO JOGO · Todas","TIPO DE SPOT · Todos","APENAS RANGES GTO","INCLUIR ICM","MODO DESAFIO"].map(x=><button key={x}>{x}<span>›</span></button>)}</div><button className="pt-apply">APLICAR FILTROS</button></P><P title="◉ TEMA"><div className="pt-list">{["◉ ROXO (STACKUP)","◉ AZUL (CLASSIC)","◉ VERDE (FOCUS)","SOM","VIBRAÇÃO","MOSTRAR EV","DICAS EM TEMPO REAL","MODO CANHOTO","IDIOMA · Português (BR)","SOBRE"].map(x=><button key={x}>{x}<span>●</span></button>)}</div></P></div>
 <footer><div className="pt-footbrand"><b>SH</b><span>STACKUP HOLD’EM<small>PRO TRAINER</small></span></div><strong>“TRAIN SMARTER.<br/>PLAY BETTER”</strong><span>CONTEÚDO EDUCACIONAL<br/>SEM APOSTAS</span></footer></main>
}